name: Zhicong Lu
author: Zhicong Lu
baseurl:
description: Research Assistant in HCI University of Toronto
github: http://www.github.com/luzc08
twitter: http://www.twitter.com/luzc08
facebook: http://www.facebook.com/calebluzc
linkedin: https://www.linkedin.com/in/luzc08
google-plus: https://plus.google.com/+%E9%99%86%E5%BF%97%E8%81%AA/posts/p/pub
email: luzhc[at]cs.toronto.edu
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
